"""empty message

Revision ID: 3230c615d6e0
Revises: 
Create Date: 2017-08-01 04:48:27.965959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3230c615d6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('probe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guilty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guilty_blacklisted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('kernel_version', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('record_format_version', sa.Integer(), nullable=True),
    sa.Column('payload_format_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('tsp', sa.Integer(), nullable=True),
    sa.Column('tsp_server', sa.Integer(), nullable=True),
    sa.Column('buildstamp', sa.String(), nullable=True),
    sa.Column('backtrace', sa.String(), nullable=True),
    sa.Column('dupe_of', sa.Integer(), nullable=True),
    sa.Column('dupecount', sa.Integer(), nullable=True),
    sa.Column('dupemaster', sa.Boolean(), nullable=True),
    sa.Column('security', sa.Boolean(), nullable=True),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('guilty_id', sa.Integer(), nullable=True),
    sa.Column('external', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['classification_id'], ['classification.id'], ),
    sa.ForeignKeyConstraint(['guilty_id'], ['guilty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('guilty_blacklisted')
    op.drop_table('guilty')
    op.drop_table('classification')
    op.drop_table('build')
    # ### end Alembic commands ###
