"""empty message

Revision ID: cb72058cf4e4
Revises: 466cf2f35d67
Create Date: 2018-03-08 23:44:09.063261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb72058cf4e4'
down_revision = '466cf2f35d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'event_id')
    # ### end Alembic commands ###
